### ISSUE TITLE
Problem with single-point corrections with same extension as opt files

### ISSUE THREAD

**Issue by jvalegre** [patonlab/GoodVibes#31]
Just a reminder - just installed the newest version of GV from scratch from pip, but I still get a problem with --spc. If FILE and FILE_SPC are both ".log" (i.e. FILE.log and FILE_QZ.log). I get this error:
"Error! SPC calculation file 'Int_I_ar02_am01_PP01_qz_qz' not found! Make sure files are named with the convention: 'filename_spc'."

**Comment by luchini18** [comment]
Hello! This issue has been resolved in the newest version of GoodVibes. If you uninstall the program using conda with `conda uninstall goodvibes` then download the newest version from the GitHub page and install with `python setup.py install` from the newly downloaded folder, it should update your code to the most recent version.

**Comment by Xiangyang2017** [comment]
Yes, It workes well on my mac. However, I still have this problem when I am running goodvibes in Linux system. 

goodvibes -q --spc SP *.out

Error! SPC calculation file 'INT4_RE0_A_SP_SP' not found! Make sure files are named with the convention: 'filename_spc'.
For help, use option '-h'
